- .travis.yml
since we used sudo only for testing installation, it might work without
sudo
> ENH: try to use new container based Travis infrastructure

- duecredit/__init__.py
- duecredit/injections/injector.py
Before at `import duecredit` it would fail because in `__init__.py` it calls the injector, and the injector called `from duecredit import due` but at that point wasn't existing yet.
> BF: circular import of injector and duecredit

- duecredit/io.py
Fixes #23 
Now the output is:
```
DueCredit Report:
- numpy (v 1.9.2) [1]
- mvpa2 (v 2.4) [2]
- mvpa2.featsel.rfe:_train (Recursive feature elimination procedure) [3]
- mvpa2.algorithms.group_clusterthr:_train (Statistical assessment of (searchlight) MVPA results) [4]
- mvpa2.clfs.transerror:_call (Bayesian hypothesis testing) [5]
2 modules cited
2 functions cited
References
----------
[1] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
[2] Hanke, M. et al., 2009. PyMVPA: a Python Toolbox for Multivariate Pattern Analysis of fMRI Data. Neuroinformatics, 7(1), pp.37–53.
[3] Guyon, I. et al., 2002. Gene Selection for Cancer Classification using Support Vector …
```
> BF: give correct ref numbers for citations

- duecredit/injections/injector.py
- duecredit/tests/test_injections.py
primarily driven by difficulty to rely on __del__ being invoked. gc might delay picking up all the objects for various reasons (e.g. binding to decorated __import)
> Few tune ups to injection and more to its testing

- duecredit/collector.py
- duecredit/injections/mod_numpy.py
- duecredit/io.py
- duecredit/tests/test_collector.py
or might be just referencing a library/package while decorating a method,
so pretty much that citation would only trigger upon use, BUT because it is
a citation for a package -- it would not trigger unless explicitly tagged.
So we pretty much might like to add that tag withing dcite since it guarantees
that function gets called/citation must be in place (TODO: think more about it)
May be you see a better name for this tag @mvdoc ?
> RF: cite-on-import -> cite-module  since we might be dealing with other languages etc

- duecredit/collector.py
- duecredit/entries.py
- duecredit/injections/mod_scipy.py
- duecredit/io.py
- duecredit/stub.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_io.py
Took me a while, but works. It could be made prettier though.
Fixes #30, passes #32.
The biggest change is that now `path` must be specified in the citation (or we have to get it automatically), because the citation is stored according to a tuple `(path, entry_key)`.
> REF: text output, divide "model" from "view"

- duecredit/io.py
will look now like
```
$> duecredit summary
DueCredit Report:
- LIBSVM: A library for support vector machines / libsvm (v None) [1]
- Multivariate pattern analysis of neural data / mvpa2 (v 2.4) [2]
- Support Vector Machines (SVM) / mvpa2.clfs.SVM (v 2.4) [3]
- Sparse multinomial-logistic regression classifier / mvpa2.clfs.smlr:SMLR (v 2.4) [4]
- Bayesian hypothesis testing / mvpa2.clfs.transerror:_call (v 2.4) [5]
- Recursive feature elimination procedure / mvpa2.featsel.rfe:_train (v 2.4) [6]
- Searchlight analysis approach / mvpa2.measures.searchlight:_call (v 2.4) [7]
- Scientific tools library / scipy (v 0.14.1) [8]
- Machine Learning library / sklearn (v 0.16.1) [9]
- Random forest classifiers / sklearn.ensemble.forest:RandomForestClassifier.predict_proba (v 0.16.1) [10]
- …
```
> BF: print description, not just path. Closes #49

- duecredit/collector.py
- duecredit/tests/test_collector.py
This should allow for conditioning citation based on the status of the object (usually passed as the first argument (`self`) to the method call
> Overhaul conditions -- "and" logic (all must be met) + allow to access attributes of the arguments

- duecredit/collector.py
- duecredit/io.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_io.py
We're getting there... however there is still a problem with the injector because there should be two citations for spectral clustering (see below), but only one appears...probably due to how they're stored. Will look into that.
```
(duecredit)contematto@talete ~/github/scikit-learn/examples/cluster (master*) $ python -m duecredit plot_cluster_comparison.py
=========================================================
Comparing different clustering algorithms on toy datasets
=========================================================
This example aims at showing characteristics of different
clustering algorithms on datasets that are "interesting"
but still in 2D. The last dataset is an example of a 'null'
situation for clustering: the data is homogeneous, and
there is no good clustering.
While …
```
> BF: Fix get_text_rendering when Citation is passed with Doi

- duecredit/io.py
- duecredit/tests/test_io.py
> BF: workaround for zenodo bibtex entries imported with import_doi

- duecredit/injections/injector.py
- duecredit/tests/test_injections.py
- setup.py
now also avoids side-effect of del resetting orig_import when it mustn't
Closes #88 #47 #90
> BF: allow multiple injections at the same path, avoid resetting _orig_import if already deactivated

- README.md
> DOC: Update readme to reflect current output of duecredit summary

- duecredit/dueswitch.py
- duecredit/io.py
Closes #104 
I am yet not sure why `pip install duecredit` fetching it from pypi manages to invoke `_get_active_due` but  it seems to be the case. Moving in hope to get it resolved
> BF: do not create cache directory until needed

- duecredit/tests/test_io.py
Trying to resolve #119 
I noticed that even without any changes, the test in question passes for me locally (python 3.6), so the errors may have been due to some temporary issue with querying zenodo.
I copy-pasted the output of format_bibtex() into the function test_format_bibtex_with_utf_characters(), so that this test won't fail when there is a problem with that zenodo query (rather than a problem with handling utf-8 in format_bibtex(), which we are explicitly testing for) - similar to what was done in test_format_bibtex_zenodo_doi().
On the other hand, perhaps testing whether import_doi() is successful should still be done?
> ENH: stop using import_doi when testing format_bibtex with utf8

- README.md
MDAnalysis will support duecredit natively in the upcoming 0.18.0 release (see MDAnalysis/mdanalysis#412 and details in PR MDAnalysis/mdanalysis#1822 – namely we had to mock out duecredit's use of `os.fork` to avoid complications when running under MPI)
> added MDAnalysis as native duecredit user

- duecredit/io.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_import_doi
- duecredit/tests/test_io.py
Hello!
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that recommendation by updating static DOI links, as well as code that generates new ones.
Cheers :-)
> Link DOIs to preferred resolver

- duecredit/io.py
Packages that load duecredit pull in 326 modules, 312 of which are loaded with requests.
This change delays import of requests to the single function that requests is called from.
> ENH: Delay import of requests

- duecredit/injections/injector.py
Well, duecredit should be stealth! but I ran into the case with datalad:
$> rm .duecredit.p; DUECREDIT_ENABLE=1 python -m nose -s -v datalad/support/tests/test_gitrepo.py:test_GitRepo_gitignore                                                                                                                    datalad.support.tests.test_gitrepo.test_GitRepo_gitignore ... ok
...
Exception AttributeError: "NoneType object has no attribute debug" in <bound method DueCreditInjector.__del__ of <duecredit.injections.injector.DueCreditInjector object at 0x7f5e169264d0>> ignored
so decided to silence it all.  It should be benign since seems to happen
only at the end of the process so there should be no harm of not fully
deactivating the injector
> ENH: wrap every operation in __del__ with bare try/except to avoid any error

- duecredit/io.py
- duecredit/utils.py
There is still a bunch left by running the tests but they seems all to be of not our problem
> Address a few deprecation warnings

- duecredit/io.py
- duecredit/versions.py
Elderly me forgot details of the issue since it happened years ago.
So to get better idea when things fail - provide information that it
is due to outdated citeproc
> ENH: Provide more informative message whenever using older citeproc without encoding arg

- duecredit/dueswitch.py
- duecredit/tests/test_api.py
- duecredit/tests/test_dueswitch.py
Unfortunately could no longer reproduce locally #142, and changes in 0.6.5 made it avoidable anyways.  But with these changes we should have a better chance to avoid similar gotchas
Closes #142
> Blow to initiate DueSwitch if either of collectors is None - so stub would choose InactiveCollector

- duecredit/stub.py
Discovered while testing with datalad using py3
> BF: match also for ModuleNotFoundError to not log error

- duecredit/entries.py
- duecredit/tests/test_entries.py
Note that inequality comparison cannot be done on stubbed do_nothing
returned values.  We could have returned provided `*args`, `**kwargs` but
that would only add tiny performance load and not sure if would not
cause some side-effects.
> ENH: provide equality comparison for entries

- duecredit/stub.py
ModuleNotFoundError is a subclass of ImportError:
https://docs.python.org/3/library/exceptions.html#exception-hierarchy
so we can safely check via isinstance.  Moreover, it seems that
whenever exception is raised without explicit instantiation
(raise ImportError), we do catch an instance, so should work fine.
And I found not explicit comment or commit description on why I used `type().__name__` here, may be just some paranoia
Thanks @effigies for the review/comment at https://github.com/duecredit/duecredit/pull/149#discussion_r264696840
> RF: use isinstance instead of type().__name__ comparison

- .travis.yml
- appveyor.yml
- duecredit/tests/test_injections.py
This pull request fixes #155 
~~there might be more to fix~~
> BF(TST): list expected entries in sorted order (fix for matplotlib) + RF appveyor config

- duecredit/io.py
but also just want to see if CI is currently passing or not upon a PR
> ENH: added a debug message to report details of the request to doi.org

- duecredit/entries.py
- duecredit/injections/mod_numpy.py
- duecredit/injections/mod_scipy.py
- duecredit/tests/test_io.py
Besides other possible effects,  leads outside code to expose this to the users.  Hopefully I caught all.  `citeproc` 0.5.1 has more to fix
> BF: declare strings using \ as r

- duecredit/versions.py
- setup.py
This PR replaces the need to add setuptools as a runtime dependency in #175.
> Replace pkg_resource with importlib.metadata

- .autorc
- .github/workflows/release.yml
- .travis.yml
- CHANGELOG.md
This PR needs to be accompanied by the following changes:
> Set up intuit auto to automate releases

- duecredit/cmdline/helpers.py
- duecredit/collector.py
- duecredit/dueswitch.py
- duecredit/entries.py
- duecredit/injections/injector.py
- duecredit/io.py
- duecredit/log.py
- duecredit/parsers.py
- duecredit/stub.py
- duecredit/tests/mod/imported.py
- duecredit/tests/mod/submod.py
- duecredit/tests/test__main__.py
- duecredit/tests/test_api.py
- duecredit/tests/test_cmdline.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_entries.py
- duecredit/tests/test_injections.py
- duecredit/tests/test_io.py
- duecredit/tests/test_utils.py
- duecredit/tests/test_versions.py
- duecredit/utils.py
- duecredit/versions.py
- setup.py
https://wiki.debian.org/Python3-six-removal
https://github.com/duecredit/duecredit/commit/523f54742b8d38ced03ad3d37ef3a061f8c6e544)
(ok i i did not read /CONTRIBUTING.md but I'm catching up...)
> RF: remove remaining usage of SIX, and thus move away fully from Python 2

- README.md
- duecredit/config.py
This pull request makes the DUECREDIT_FILE config variable environment dependent but otherwise doesn't interfere with normal operation
> This super simple PR allows programmers to more easily create (manage) pipeline specific .duecredit.p files / reports

- .github/workflows/test.yml
Pip-installing codecov is superfluous when using the codecov action.
> Don't `pip install codecov`

- .coveragerc
- tox.ini
- Moves the coverage configuration from `.coveragerc` to `tox.ini`, next to the rest of the testing configuration
- Corrects the coverage configuration by removing the `include` key (ignored when `source` is set), thereby eliminating a warning
- Eliminates the `cover` testenv in favor of always using `pytest-cov` in the default testenv
> Better coverage config

- .github/workflows/test.yml
- appveyor.yml
<https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html>
> Stop executing `setup.py`

- duecredit/entries.py
or may be I am missing some known pattern for such `__eq__`s?
> raise, do not return some NotImplemented if type is other than what we can compare

- duecredit/versions.py
- setup.py
This is unnecessary now that duecredit requires Python 3.8+.
> Remove use of importlib.metadata backport

- duecredit/stub.py
- duecredit/tests/mod/submod.py
- duecredit/tests/test_api.py
- duecredit/tests/test_collector.py
- duecredit/utils.py
- duecredit/versions.py
So I continue adding type annotations, more commits will follow
> add more type annotations

- duecredit/log.py
That could prevent interaction with downstream libraries which import duecredit first thing in their life cycle.  And since then they might rely on stdout to be used for actually useful content, we better not to pollute it.
Underlying trigger for such a fix:
- https://github.com/dandi/dandi-cli/issues/1441
Release is needed as we have not released for awhile and downstream needs 3.12 compatibility etc
> Log to stderr not stdout by default

- .github/workflows/test.yml
- duecredit/injections/injector.py
- duecredit/tests/envs/nolxml/lxml.py
- duecredit/tests/test_api.py
It is quite heavy in terms of dependencies so there is a good chance that pip install would fail and it masks our possibly failures while trying to test having more popular dependencies installed
E.g. currently it fails with
```
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DUSE_PORTAUDIO -DUSE_PORTMIDI -DUSE_OSC -Iinclude -I/usr/include -I/usr/local/include -I/opt/hostedtoolcache/Python/3.12.3/x64/include/python3.12 -c src/engine/ad_portaudio.c -o build/temp.linux-x86_64-cpython-312/src/engine/ad_portaudio.o -Wno-strict-prototypes -Wno-strict-aliasing -O3 -g0 -DNDEBUG
In file included from src/engine/ad_portaudio.c:21:
include/ad_portaudio.h:25:10: fatal error: portaudio.h: No such file or directory
25 | #include "portaudio.h"
|          ^~~~~~~~~~~~~
compilation …
```
> Do not bother testing with psychopy installed

- setup.py
This was maybe usefull until Python 3.3
> remove last reference to contextlib2

- README.md
> Travis is not used anymore

- duecredit/utils.py
Detected using ruff/flake8-bugbear ruleset (B):
B018 Found useless expression. Either assign it to a variable or remove it.
From initial commit 30cba62.
> Do call print()

- duecredit/injections/injector.py
- duecredit/log.py
- duecredit/tests/test_api.py
- duecredit/utils.py
PLW1508 Invalid type for environment variable default; expected `str` or `None`
> Apply ruff/Pylint Warning rules

- duecredit/io.py
C414 Unnecessary `list()` call within `sorted()`
> Start applying ruff/flake8-comprehensions rules

- duecredit/cmdline/helpers.py
- duecredit/injections/injector.py
* [deprecated-import (UP035)](https://docs.astral.sh/ruff/rules/deprecated-import/#deprecated-import-up035)
* [quoted-annotation (UP037)](https://docs.astral.sh/ruff/rules/quoted-annotation/#quoted-annotation-up037)
> Start applying ruff/pyupgrade rules

- duecredit/collector.py
- duecredit/dueswitch.py
E713 Test for membership should be `not in`
> Apply ruff/pycodestyle rule E713

- duecredit/__main__.py
- duecredit/cmdline/cmd_summary.py
- duecredit/cmdline/helpers.py
- duecredit/cmdline/main.py
- duecredit/collector.py
- duecredit/dueswitch.py
- duecredit/injections/injector.py
- duecredit/io.py
- duecredit/log.py
- duecredit/stub.py
- duecredit/tests/mod/imported.py
- duecredit/tests/mod/submod.py
- duecredit/tests/test__main__.py
- duecredit/tests/test_cmdline.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_injections.py
- duecredit/tests/test_io.py
- duecredit/tests/test_utils.py
- duecredit/tests/test_versions.py
- duecredit/utils.py
- duecredit/versions.py
- setup.py
UP031 Use format specifiers instead of percent format
UP032 Use f-string instead of `format` call
> Apply ruff/pyupgrade rules UP031/UP032: .format instead of % + prefer f-strings

- .github/workflows/test.yml
- .pre-commit-config.yaml
- duecredit/cmdline/__init__.py
- duecredit/cmdline/cmd_summary.py
- duecredit/cmdline/common_args.py
- duecredit/cmdline/helpers.py
- duecredit/cmdline/main.py
- duecredit/collector.py
- duecredit/dueswitch.py
- duecredit/injections/__init__.py
- duecredit/injections/injector.py
- duecredit/injections/mod_biosig.py
- duecredit/injections/mod_nibabel.py
- duecredit/injections/mod_nipy.py
- duecredit/injections/mod_numpy.py
- duecredit/injections/mod_pandas.py
- duecredit/injections/mod_scipy.py
- duecredit/injections/mod_sklearn.py
- duecredit/stub.py
- duecredit/tests/mod/submod.py
- duecredit/tests/test_api.py
- pyproject.toml
- tox.ini
This pull request fixes #231.
Requires #232 to be merged first, then rebase.
I'd like to switch from `setup.cfg` to `pyrproject.toml` later on, so maintain ruff configuration in `pyproject.toml`.
> Add ruff to pre-commit config

- duecredit/io.py
- duecredit/utils.py
PIE810 Call `startswith` once with a `tuple`
> Start applying ruff/flake8-pie rules

- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
This pull request fixes https://github.com/duecredit/duecredit/pull/234#issuecomment-2766818431.
Replace `isort` with `ruff check` and the isort (`I`) ruleset.
The pre-commit/tox.ini stuff is inspired by:
https://docs.releng.linuxfoundation.org/en/latest/best-practices.html#set-up-pre-commit-for-a-project
> isort → ruff
