duecredit/duecredit

- README.md
- duecredit/collector.py
- duecredit/io.py
- duecredit/tests/test_api.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_io.py
Aims to Close #8 
May be that was too much with "desc" but "use" also sounded a bit inappropriate
> RF arguments for cite:  kind -> tags, level -> path, use -> desc

- duecredit/injections/mod_numpy.py
- duecredit/injections/mod_scipy.py
- duecredit/injections/mod_sklearn.py
- duecredit/tests/test_injections.py
- examples/example_scipy.py
Starting to add more -- shall we also add specific functions?
> [WIP] Start adding more injections

- duecredit/tests/test_io.py
> TST: check reference numbers are consistent

- duecredit/collector.py
- duecredit/injections/mod_sklearn.py
- duecredit/io.py
> [Injections] Add all references for sklearn.cluster

- duecredit/injections/injector.py
Somewhat ugly but hopefully would resolve the issues with possibly "buggy" operation of some Pythons
> ENH+DOC: always check if _orig_import is not None (Closes #40)

- duecredit/io.py
- duecredit/tests/test_io.py
It was actually easier than we thought. Kudos to @davidagraf and code in https://github.com/davidagraf/doi2bib/blob/master/app/doi2bib.js 
closes #73 and #72
> BF: change request command to make it work with zenodo too

- README.md
> DOC: Show that user can also enter BibTeX entries

- .gitignore
- appveyor.yml
- duecredit/cmdline/main.py
- duecredit/io.py
- duecredit/tests/test__main__.py
- duecredit/tests/test_api.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_import_doi
- duecredit/tests/test_injections.py
- duecredit/tests/test_io.py
- duecredit/tests/test_versions.py
- duecredit/tests/utils.py
- duecredit/utils.py
- requirements.txt
- setup.py
- tox.ini
It will fail and we would need to resolve those failing tests/code, see 
https://ci.appveyor.com/project/yarikoptic/duecredit-ml895/build/1.0.1
which was ran under my account.
> ENH: appveyor configuration (based on shablona's) based on mix of conda and pip

- README.md
- duecredit/io.py
- duecredit/tests/test_io.py
> ENH: support DUECREDIT_REPORT_ALL=1 to report all citations, not only with functionality used

- duecredit/io.py
also added notes that with freshier citeprocpy we could export bib as utf-8
> ENH: workaround for pages handling fixed in citeproc post 0.3.0

- README.md
Moved the "Last updated" line after the list, because I think it looks better. Feel free to disagree and I'll revert it.
> Add Quickshear to "Currently used by" list

- README.md
Hey guys!
Good job on gettting started in trying to solve this important problem. I appreciate the motivation and support the ideas. 
But the README was difficult for me to follow, so I tried to improve it. I'm not sure if I even understand it correctly, this is to try improve it for everyone. Please feel free to correct and expand it as you see it.
I will add this to my software once I get a handle on it.
Pradeep
> Improved Introduction to duecredit

- README.md
Hi, cool project.
I have just added a missing word, fixed a few inconsistent capitalizations and removed some redundant double scapes in the readme file.
> Small fixes in readme.

- duecredit/__init__.py
- duecredit/dueswitch.py
- duecredit/entries.py
- duecredit/io.py
- duecredit/stub.py
- duecredit/tests/test_collector.py
- duecredit/tests/test_io.py
Would just spit out without rendering in text format and complain for BibTex.
Also provide "custom" text rendering for URL
> ENH: Support for (free style) Text entry + Exposing DueSwitch's methods within InactiveCollector in the stub

- duecredit/injections/mod_matplotlib.py
- duecredit/tests/test_injections.py
- Hunter 2007 publication
- Zenodo DOI which will always point to latest version
> Add Matplotlib injection

- .github/PULL_REQUEST_TEMPLATE.md
- .zenodo.json
@emirvine  please see if you would like to adjust your entry in the file.  Unfortunately ATM I do not have time to hunt for all github ids to notify for others to do the same
> ENH: provide zenodo.json and a PR template asking contributor to add him/herself to that file

- README.md
See #166.
Thanks again, @yarikoptic.
> Add TorchIO to "Currently used by" list

- duecredit/stub.py
As requested [here](https://github.com/dandi/dandi-cli/pull/657#discussion_r647411427).
> Tell LGTM to ignore unused imports in stub.py

- setup.py
Python versions like `0.9.1.debian1` or `0.9.1.debian1ubuntu1` are not PEP440 compliant. With setuptools 66, the versions of all packages visible in the Python environment *must* obey PEP440.
Bug: https://github.com/pypa/setuptools/issues/3772
Bug-Ubuntu: https://launchpad.net/bugs/1991606
> Make Debian Python version PEP440 compliant

- README.md
This pull request is in response to issue #188 (it's only a README change, no functional changes are made)
> Add some more `cite()` information to the README.md

- .github/workflows/test.yml
- duecredit/injections/injector.py
- duecredit/tests/test_versions.py
Closes #214
Thanks @mikemhenry for the report!
> Fix assertion placement + test on CI having numpy installed in a separate matrix run

- .github/workflows/test.yml
> Test against Python 3.13

- duecredit/versions.py
SIM101 Multiple `isinstance` calls, merge into a single call
> Start applying ruff/flake8-simplify rules

- duecredit/tests/test_injections.py
PLR0402 Use `from duecredit.tests import mod` in lieu of alias
> Start applying ruff/Pylint Refactor rules

- duecredit/collector.py
- duecredit/entries.py
RUF010 Use explicit conversion flag
> Start applying ruff rules: RUF010 Use explicit conversion flag

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- duecredit/__init__.py
- duecredit/cmdline/helpers.py
- duecredit/injections/injector.py
- duecredit/io.py
- duecredit/tests/mod/__init__.py
- duecredit/tests/test_api.py
- duecredit/tests/test_cmdline.py
- duecredit/tests/test_collector.py
- duecredit/utils.py
- pyproject.toml
- tox.ini
This pull request fixes https://github.com/duecredit/duecredit/pull/234#issuecomment-2766818431.
> flake8 → ruff
